# netlify.toml

# Этот раздел настраивает ваши Edge Functions
[[edge_functions]]
# Путь, по которому будет применяться эта Edge Function.
# "/*" означает, что она будет срабатывать на все запросы к вашему сайту.
path = "/*"
# Имя вашей Edge Function, соответствует имени файла JavaScript без расширения .js
function = "check-referer-v2"
